name: dino_wm
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - ffmpeg
  - matplotlib
  - numpy=1.26
  - gymnasium
  - pybullet
  - hydra-core
  - omegaconf
  - pillow
  - scikit-image
  - opencv
  - ipython
  - ipykernel
  - jupyterlab
  - jupyter
  - pip:
      - anyio==4.5.2
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - black==24.8.0
      - bleach==6.1.0
      - cloudpickle==3.1.1
      - gym==0.26.2
      - gym-notices==0.0.8
      - httpx==0.28.1
      - matplotlib-inline==0.1.7
      - nbconvert==7.16.6
      - notebook==7.3.3
      - pytest==8.3.5
      - shapely==2.0.7
      - torch==2.2.2
      - hydra-submitit-launcher==1.2.0
      - torchvision==0.17.2
      - wandb==0.13.1
      - miniworld @ git+https://github.com/pythonpedro99/JEPAWorld.git@9c56fc6f7b7b1455d1551a944865bb937011e645#egg=miniworld&subdirectory=Miniworld
      - submitit
      - einops
