name: rearrange
args: []
kwargs: {}

dataset:
  _target_: "datasets.rearrange_dset.load_rearrange_slice_train_val"
  n_rollout: null
  normalize_action: ${normalize_action}
  data_path: ${oc.env:DATASET_DIR}/rearrange_2000
  split_ratio: 0.9
  filter_train: false
  filter_val: false
  n_slices_train: 22500
  n_slices_val: 2500
  filter_actions: [4, 5]
  seed_train: 42
  seed_val: 99
  verbose: false
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}

decoder_path: null
num_workers: 16